version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "maintainer"
    assignees:
      - "maintainer"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  # Enable version updates for frontend dependencies
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Enable version updates for API dependencies
  - package-ecosystem: "npm"
    directory: "/services/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"