name: API Services CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - 'services/**'
      - 'packages/**'
      - '.github/workflows/api-services.yml'
  pull_request:
    branches: [main]
    paths:
      - 'services/**'
      - 'packages/**'

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          cd services/api && npm ci
          cd ../../packages/shared-types && npm ci
          cd ../validation && npm ci
      
      - name: Build shared packages
        run: |
          cd packages/shared-types && npm run build
          cd ../validation && npm run build
      
      - name: Build API service
        run: cd services/api && npm run build
      
      - name: Run tests
        run: cd services/api && npm run test

  deploy-api:
    if: github.ref == 'refs/heads/main'
    needs: test-api
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: ./tools/scripts/setup-dev.sh
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Deploy Lambda functions
        run: |
          cd infrastructure/aws-cdk
          export STAGE=prod
          npm run deploy