name: Infrastructure Deployment

on:
  push:
    branches: [main]
    paths:
      - 'infrastructure/**'
      - '.github/workflows/infrastructure.yml'
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deployment stage'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.stage || 'production' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install CDK dependencies
        run: cd infrastructure/aws-cdk && npm ci
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: CDK Bootstrap (if needed)
        run: |
          cd infrastructure/aws-cdk
          npx cdk bootstrap
      
      - name: CDK Diff
        run: |
          cd infrastructure/aws-cdk
          export STAGE=${{ github.event.inputs.stage || 'prod' }}
          npx cdk diff
      
      - name: CDK Deploy
        run: |
          cd infrastructure/aws-cdk
          export STAGE=${{ github.event.inputs.stage || 'prod' }}
          npx cdk deploy --all --require-approval never